### ISSUE TITLE
Deployement Docs

### ISSUE THREAD

**Issue by regisx001** [GlebBatykov/minerva#4]
I have Already finished a small project and i want to deploy it for test, and i had some problems when deploying the dockerfile to heroku , and my porblem is the nothing work and in the screen they tell application error .
could you make a small docs about the deployement !
and Thanks for this amazing framework

**Comment by GlebBatykov** [comment]
Hi!

I haven't used Heroku. Are you placing a docker container there?

Is docker image being assembled normally? What type of compilation do you use when building docker image? Have you added assets to the project (to the appsetting.json file)?

In general. When creating a project, a dockerfile is created. Minerva contains 2 types of dockerfile templates for 2 types of compilation, respectively: JIT and AOT. You can regenerate dockerfile using the docker command (and specify the necessary type of compilation). Also, if you add assets to the project, that is, files that should be in the final assembly, which are necessary for work, you must regenerate the dockerfile.

If you added assets to appsetting.json, then you must regenerate the dockerfile so that there are lines in the docker file with the addition of these files to the docker image.

If you are successfully building docker image, then try running docker container locally. Make sure it works and it's not about Heroku (I haven't used it, so I don't know if I need to configure the project for it in some specific way).

**Comment by GlebBatykov** [comment]
I will add more information about dockerfile and deployment to the documentation.

**Comment by regisx001** [comment]
Yes I add all the assets to the appSetting.json , Yes May be i didn't regenerate the docker file  that causing the issue , I have read the heroku docs about how to deploy a Docker Container and may be the docker regenrating that make the problem ! it will be great that you add more info about the deployement ,
Thank you for your time

**Comment by GlebBatykov** [comment]
I have added deployment information to the documentation.
